plugins {
    id 'com.android.application'
}

android {
    namespace 'com.autonoma.sysinventory'
    compileSdk 34

    defaultConfig {
        applicationId "com.autonoma.sysinventory"
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName "1.5.0"
    }

    signingConfigs {
        release {
            if (file("release.jks").exists()) {
                storeFile file("release.jks")
                storePassword "sysinventory2026"
                keyAlias "sysinventory"
                keyPassword "sysinventory2026"
                v1SigningEnabled true
                v2SigningEnabled true
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            if (file("release.jks").exists()) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
